stitching:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://em-stitching-postgres-db-aat.postgres.database.azure.com:5432/emstitch
    SPRING_DATASOURCE_USERNAME: annotation@em-stitching-postgres-db-aat
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
postgresql:
  enabled: true
