java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  readinessDelay: 45
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/javadatabase?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
    CDAM_URL: https://ccd-case-document-am-api-pr-484.service.core-compute-preview.internal
    ENABLE_LIQUIBASE: true
    ENABLE_DB_MIGRATE: true
  postgresql:
    enabled: true
