---
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://idam-web-public.aat.platform.hmcts.net/o
        registration:
          oidc:
            client-id: microservicekey-em-stitching-api
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}

test:
  url: ${TEST_URL:http://localhost:8080}

idam:
  api:
    url: ${IDAM_API_BASE_URI:http://localhost:4501}
  client:
    id: ${OAUTH_CLIENT:webshow}
    secret: ${FUNCTIONAL_TEST_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}

s2s:
  api:
    url: ${S2S_BASE_URI:http://localhost:4502}
    secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:AAAAAAAAAAAAAAAA}
    serviceName: ${S2S_SERVICE_NAME:em_gw}

document_management:
  url: ${DM_STORE_APP_URL:http://localhost:4603}

annotation:
  api:
    url: ${EM_ANNO_APP_URL:http://localhost:4623}

# Allowed audience list
oidc:
  audience-list: jui_webapp,em_ccd_orchestrator,em_gw
  issuer: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts